### ISSUE TITLE
IINA HomePod and Airplay 2

### ISSUE THREAD

**Issue by LachiePhilipson** [lhc70000/iina#1853]
**System and IINA version:**

- macOS 10.13.4
- IINA 1.0.0-beta2 (80)

Audio and video should now be in sync with Airplay 2 installed on the HomePod.

Youtube from Safari and Chrome are able to play video in sync with audio from both Macs

Quicktime can play video in sync with audio from both Macs using the same video files that are in my library

VLC and IINA will not play video in sync with audio but the same exact files play in sync from quicktime which leads me to believe this is due to airplay 2 being unsupported from IINA media player.

Audio and video are out of sync.

- Crash report:
```

```

- MPV log:
```

```

1. Airplay Audio to HomePod from within the player

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by silence-majority** [comment]
in addition to the audio delay, IINA also did not support to airplay to 2 homepods that can be tied to a entirety to play stereo audio , which itunes had supported

**Comment by pjktheking** [comment]
How long will they fix this... my HomePod...

**Comment by chucker** [comment]
Since nobody has written it, as a temporary hack, you can set the audio delay to -2 seconds. That'll be roughly right for an AirPlay 1 device.

**Comment by alphabt** [comment]
> Since nobody has written it, as a temporary hack, you can set the audio delay to -2 seconds. That'll be roughly right for an AirPlay 1 device.

You can also apply this workaround to all videos played in IINA by going to Preferences > Advanced > Enabled advanced settings > Add new mpv option with name `audio-delay` and value `-2`.

![image](https://user-images.githubusercontent.com/6440237/101267716-c8e4ec00-3796-11eb-9959-16757a8429ac.png)

**Comment by PhilipMok-cc** [comment]
I would like to try to solve this problem but 
I am new to this project would like to know if my understanding is correct.
1. If mpv support airplay 2 this issue and related issue will be resolved
2. mpv does not support airplay2 at the moment?
4. iina has nothing to do if mpv did not support the airplay 2?
5. Or we add the airplay 2 support in UI layer with swift code and let apple bring the update to the backend later on?

**Comment by chucker** [comment]
There are two separate issues.

One is that AirPlay 2 would be nicer, as it would reduce latency and allow for multiple speakers.

The other is that it needs video and audio to sync up. With AirPlay 1, that’s easy enough: audio will be delayed by two seconds. With AirPlay 2, the protocol tells the app the delay. So, when switching to an AirPlay speaker, IINA should set the delay automatically.

**Comment by PhilipMok-cc** [comment]
> There are two separate issues.
> 
> One is that AirPlay 2 would be nicer, as it would reduce latency and allow for multiple speakers.
> 
> The other is that it needs video and audio to sync up. With AirPlay 1, that’s easy enough: audio will be delayed by two seconds. With AirPlay 2, the protocol tells the app the delay. So, when switching to an AirPlay speaker, IINA should set the delay automatically.

The auto setting delay should happened in the iina but the support of airplay2 should happened in mpv am I right?

**Comment by JohnnyFireOne** [comment]
@low-batt 
any news about airplay 2 support? I'm using HomePods gen 2 at the moment with the workaround -2 sec delay but we need a proper fix! please!

**Comment by low-batt** [comment]
Sorry I'm slow to respond. Overloaded and losing track of things…

I think you are asking two questions. First, the status of AirPlay support directly in IINA. That is issue #63. [This comment](https://github.com/iina/iina/issues/63#issuecomment-1162585725) discusses the technical problems with providing such support. That was from back in 2022, but I expect those same challenges still exist.

On the need to configure a -2 second audio delay, that seems wrong to me. For audio/video support IINA uses a library from the [mpv](https://github.com/mpv-player/mpv) project. IINA is involved in video, but the libmpv is fully in charge of audio. I would expect libmpv to detect the latency of the audio device and automatically delay audio appropriately.

Checking mpv issues there is a lot of discussion of this as well as some fixes. However it seemed like the fix I found should already be in IINA 1.3.5. The next step would be to try mpv 0.39.0 and see if it automatically synchronizes the audio. If not then report it to that project.

IINA is very close to releasing the first beta of the next IINA release. This release will upgrade the libmpv IINA is using. The newer version of mpv supports a new AVFoundation audio driver. That driver might properly handle the latency of AirPlay.

**Comment by JohnnyFireOne** [comment]
> Sorry I'm slow to respond. Overloaded and losing track of things…
> 
> I think you are asking two questions. First, the status of AirPlay support directly in IINA. That is issue #63. [This comment](https://github.com/iina/iina/issues/63#issuecomment-1162585725) discusses the technical problems with providing such support. That was from back in 2022, but I expect those same challenges still exist.
> 
> On the need to configure a -2 second audio delay, that seems wrong to me. For audio/video support IINA uses a library from the [mpv](https://github.com/mpv-player/mpv) project. IINA is involved in video, but the libmpv is fully in charge of audio. I would expect libmpv to detect the latency of the audio device and automatically delay audio appropriately.
> 
> Checking mpv issues there is a lot of discussion of this as well as some fixes. However it seemed like the fix I found should already be in IINA 1.3.5. The next step would be to try mpv 0.39.0 and see if it automatically synchronizes the audio. If not then report it to that project.
> 
> IINA is very close to releasing the first beta of the next IINA release. This release will upgrade the libmpv IINA is using. The newer version of mpv supports a new AVFoundation audio driver. That driver might properly handle the latency of AirPlay.

@low-batt
hello and thank you for the reply!
well the -2 seconds is vital to make the audio sync.... its apples issue with HomePods because when i use airplay 2 works as intended! i will try mpv 0.39 to see how it goes!

i tested and.....didnt change anything at all......i hope the new version of IINA will be somehow workaround this one issue...

**Comment by low-batt** [comment]
Test mpv again, this time adding `--ao=avfoundation`.

**Comment by JohnnyFireOne** [comment]
Done that but the same issue, should I trigger the setting with a config file or something? Or it’s baked in? I test it many times with no result 29 Οκτ 2024, 05:14, ο χρήστης «low-batt ***@***.***>» έγραψε:﻿
Test mpv again, this time adding --ao=avfoundation.

**Comment by JohnnyFireOne** [comment]
found it need to make a config file…. works stable but has a delay at start i think to synchronising

**Comment by low-batt** [comment]
If you added `--ao=avfoundation` to the command line that is all it takes to switch mpv to that driver. If it didn't solve the problem then there is no need to add it to a config file so it always uses that driver.

I'm disappointed. I thought the AVFoundation audio driver might handle this correctly. With all the audio support coming from `libmpv` it is hard for IINA code to workaround the problem.

**Comment by low-batt** [comment]
The next version of IINA will have the ability to change the audio driver.

**Comment by JohnnyFireOne** [comment]
> If you added `--ao=avfoundation` to the command line that is all it takes to switch mpv to that driver. If it didn't solve the problem then there is no need to add it to a config file so it always uses that driver.
> 
> I'm disappointed. I thought the AVFoundation audio driver might handle this correctly. With all the audio support coming from `libmpv` it is hard for IINA code to workaround the problem.

@low-batt 
correction i add it to the config file and works as intended!!!!
my mistake was used a preconfig that has other audio values that mess the things up...
the ao=avfoundation works!!!!!!!!!! and i hope we have it on next version of IINA!!!!!!!

**Comment by JohnnyFireOne** [comment]
> The next version of IINA will have the ability to change the audio driver.

@low-batt 

Joy to my ears!!!!!!!!!!!!!!!!!!!! till then im gonna use the mpv with this trick too!

**Comment by melkir** [comment]
For anyone coming here, the nightly release does allow to switch audio codec 👏 
However, when the "[AirPlay] avfoundation" is selected, no sound is coming out of the Homepod.
Something similar to how Optimus Player handle "AirPlay 2 Audio" would be really nice
