### ISSUE TITLE
Crash after change playback position in online stream (url) 

### ISSUE THREAD

**Issue by ww7** [lhc70000/iina#245]
Open URL, direct link to mkv file. After try to seek iina crash. 10.12.2

`System Integrity Protection: disabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000064
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]`

**Comment by lhc70000** [comment]
Thanks for feedback.

We need more information to figure out the problem:

- Does it happen every time? 
- The whole crash report
- The url you tried to play, if posible

**Comment by ww7** [comment]
- It's happen every time with all URL's
- Example any Youtube
- Example URL: http://libr.cloudns.pro/w/films/Persona.1966.BDRip-AVC.mkv
- Whole crash report: http://pastebin.com/3xDrMAdN

**Comment by lhc70000** [comment]
Sorry, it's a stupid bug in 0.0.3. I have already fixed it in develop branch.

If playing online video is an important feature to you, I'll release a new version earlier.

**Comment by ww7** [comment]
Arigato

**Comment by saagarjha** [comment]
@ww7 CLI support is tracked by #58 and #235.

**Comment by lhc70000** [comment]
Fixed in [0.0.4](https://github.com/lhc70000/iina/releases/tag/v0.0.4).

**Comment by GyD** [comment]
Exactly same issue is back in 0.0.5, you can use @ww7 examples ( https://github.com/lhc70000/iina/issues/245#issuecomment-274511950 ) to reproduce the error

**Comment by lhc70000** [comment]
@GyD Which language are you using?

**Comment by GyD** [comment]
@lhc70000 French, switching to english _fixed_ the issue

**Comment by lhc70000** [comment]
@GyD Yes, confirmed that there's a problem in French (and Traditional Chinese) translation string. Please wait for next release.
