### ISSUE TITLE
Subtitle margin not work

### ISSUE THREAD

**Issue by rapha-35** [lhc70000/iina#272]
Hi,
I am playing some MKV with ASS embedded subtitles, the position of them is a the bottom of the screen without any margins, and it's annoying to read that way.

In the app preferences, I tried to change the settings, but it did nothing.
(it works on other video with standard subtitles).

I also checked the option to ignore any styling; it does work for font and font-effects, but not for position.

It would be great to override this setting too.

Thanks.

**Comment by megadr01d** [comment]
Related/duplicate of https://github.com/lhc70000/iina/issues/220.

**Comment by rapha-35** [comment]
I found a way to fix that.

Should I do a Pull request ? like it's one settings change in the MPVController ...
I'll try to take a look at issue #220

**Comment by rapha-35** [comment]
MPVController :
Changed "force" to "strip" to completely ignore ALL styling from the ASS file.  

```
setUserOption(PK.ignoreAssStyles, type: .other, forName: MPVOption.Subtitles.subAssStyleOverride) { key in
      let v = UserDefaults.standard.bool(forKey: key)
      return v ? "strip" : "yes"
    }
```

**Comment by lhc70000** [comment]
This option affects other settings. If mpv requires it to be strip in order to enable margin for ASS, maybe we need to set it at runtime manually. I'm busy today so will take a look few hours later.

**Comment by rapha-35** [comment]
Ok thanks !
I did check MPV documentation and tried some sub-ass-force-margins and sub-use-margins without success though.

**Comment by lhc70000** [comment]
@rapha-35 

`sub-use-margins`+`sub-ass-force-margins` are useful to display subtitles in letterbox (IINA will support it in 0.0.4).

Checked the document and seems that same as other `--sub-*` options, it only affects text subtitles; and `--sub-pos` is what we need.

I'll add it to settings in 0.0.4.

**Comment by lhc70000** [comment]
Fixed in [0.0.4](https://github.com/lhc70000/iina/releases/tag/v0.0.4).

Please use "subtitle position" in quick settings panel.

**Comment by rapha-35** [comment]
I don't think it's fixed, I do have this Suits episode with embedded subtitles, and they're displayed with a special style, font and color, I can't even scale it down using the menu items or the quick settings panel.

**Comment by lhc70000** [comment]
Subtitle position and scale should work for ASS subtitles.

Perhaps the subtitle of your file is image subtitle, which is basically cannot be formatted. Could you provide more information of the file?

**Comment by rapha-35** [comment]
Maybe it'll be great to be able to scale those images subtitles as we want ? for now, they're scaling with the window
