### ISSUE TITLE
Cannot switch username and password using TAB key when in Open URL dialog

### ISSUE THREAD

**Issue by legendtang** [lhc70000/iina#663]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.9

**Expected behavior:**

![image](https://cloud.githubusercontent.com/assets/1352729/26218558/08712b0c-3c3e-11e7-99c6-a23545fdd931.png)

Should be able to switch input field using TAB

**Actual behavior:**
It does not.

- Crash report:
```
N/A
```

- MPV log:
```
N/A
```

**Steps to reproduce:**
N/A

**How often does this happen?**
N/A

**Comment by alejx** [comment]
@lhc70000 Just a remainder, please also fix other textfields other than this.

**Comment by lhc70000** [comment]
Fixed in develop branch.

**Comment by alexander-ii** [comment]
@lhc70000 I'm using IINA 0.0.15 build 68 on Mac OS 10.3.3 and it still reproduces.
